// Code generated by "stringer -type=DataTypes"; DO NOT EDIT.

package df

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DTunknown-0]
	_ = x[DTstring-1]
	_ = x[DTfloat-2]
	_ = x[DTint-3]
	_ = x[DTcategorical-4]
	_ = x[DTdate-5]
	_ = x[DTnone-6]
	_ = x[DTdf-7]
	_ = x[DTconstant-8]
	_ = x[DTany-9]
}

const _DataTypes_name = "DTunknownDTstringDTfloatDTintDTcategoricalDTdateDTnoneDTdfDTconstantDTany"

var _DataTypes_index = [...]uint8{0, 9, 17, 24, 29, 42, 48, 54, 58, 68, 73}

func (i DataTypes) String() string {
	if i >= DataTypes(len(_DataTypes_index)-1) {
		return "DataTypes(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataTypes_name[_DataTypes_index[i]:_DataTypes_index[i+1]]
}
