// Code generated by "stringer -type=DataTypes"; DO NOT EDIT.

package df

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DTstring-0]
	_ = x[DTfloat-1]
	_ = x[DTint-2]
	_ = x[DTcategory-3]
	_ = x[DTdate-4]
	_ = x[DTdateTime-5]
	_ = x[DTtime-6]
	_ = x[DTslcString-7]
	_ = x[DTslcFloat-8]
	_ = x[DTslcInt-9]
	_ = x[DTany-10]
	_ = x[DTunknown-11]
}

const _DataTypes_name = "DTstringDTfloatDTintDTcategoryDTdateDTdateTimeDTtimeDTslcStringDTslcFloatDTslcIntDTanyDTunknown"

var _DataTypes_index = [...]uint8{0, 8, 15, 20, 30, 36, 46, 52, 63, 73, 81, 86, 95}

func (i DataTypes) String() string {
	if i >= DataTypes(len(_DataTypes_index)-1) {
		return "DataTypes(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataTypes_name[_DataTypes_index[i]:_DataTypes_index[i+1]]
}
