// Code generated by "stringer -type=ReturnTypes"; DO NOT EDIT.

package df

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RTscalar-83]
	_ = x[RTcolumn-67]
	_ = x[RTdf-68]
	_ = x[RTplot-80]
}

const (
	_ReturnTypes_name_0 = "RTcolumnRTdataFrame"
	_ReturnTypes_name_1 = "RTplot"
	_ReturnTypes_name_2 = "RTscalar"
)

var (
	_ReturnTypes_index_0 = [...]uint8{0, 8, 19}
)

func (i ReturnTypes) String() string {
	switch {
	case 67 <= i && i <= 68:
		i -= 67
		return _ReturnTypes_name_0[_ReturnTypes_index_0[i]:_ReturnTypes_index_0[i+1]]
	case i == 80:
		return _ReturnTypes_name_1
	case i == 83:
		return _ReturnTypes_name_2
	default:
		return "ReturnTypes(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
